version: '3.7'
services:
  ui:
    build: ./ui
    ports:
      - '3000:3000'
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - '8081:8081'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  jenkins:
      build: ./
      ports: 
      - '8080:8080'
      - '50000:50000'

